#!/usr/bin/env perl

use warnings;
use strict;

use feature qw/say/;

use File::Temp qw/tempfile tempdir/;

my $preprocessed = qx!./get_preprocessed -p!;
my $tempdir = tempdir(TMPDIR => 1, CLEANUP => 0);
open my $fh, '>', "$tempdir/sources.c";
print $fh $preprocessed;
close $fh;

my $xml = qx!lizard -X $tempdir!;
print STDOUT $xml;



