#!/usr/bin/env perl

my $cpanfile = shift @ARGV;

if ($cpanfile) {
   die "usage: debian-list-deps <abs-path-to-cpanfile> <cpanfile-dump args>"
   unless -r $cpanfile;
} else {
   die "usage: debian-list-deps <abs-path-to-cpanfile> <cpanfile-dump args>";
}

unless (@ARGV) {
   push @ARGV, '--with-all-features';
}
my $cpanfile_dump_args = join(' ',  @ARGV);

my @deps;
foreach (qx(cpanfile-dump $cpanfile_dump_args $cpanfile)) {
   chomp;
   if ($_ eq 'Starman') {
      push @deps, $_;
   } else {
      push @deps, 'lib' . ($_ =~ s/::/-/gr) . '-perl';
   }
}
my $grep_filter = '\<\(' . join('\|', @deps) . '\)\>';
my @list = qx(apt-cache pkgnames | grep -i '$grep_filter');
print (sort @list);
