#!/usr/bin/env perl

my $cpanfile = shift @ARGV;

if ($cpanfile) {
   die "usage: fedora-list-deps <abs-path-to-cpanfile> <cpanfile-dump args>"
      unless -r $cpanfile;
} else {
   die "usage: fedora-list-deps <abs-path-to-cpanfile> <cpanfile-dump args>";
}

unless (@ARGV) {
   push @ARGV, '--with-all-features';
}
my $cpanfile_dump_args = join(' ',  @ARGV);

my @deps;
foreach (qx(cpanfile-dump $cpanfile_dump_args $cpanfile)) {
   chomp;
   push @deps, 'perl-' . ($_ =~ s/::/-/gr);
}
my @list = map {if (m/^perl-[\w+\.\-]++/p) {${^MATCH}} else {()}} qx(dnf list @deps);
print join("\n", @list) . "\n";
