#!/usr/bin/env perl

use FindBin;

sub read_file
{
   open my $fh, '<', "$_[0]"
      or die "Can't open file $_[0]: $!\n";
   my @str = <$fh>;
   close $fh;
   @str;
}

my @deps;
foreach (read_file "$FindBin::Bin/../cpanfile") {
   if (m/'([^']+)'/) {
      push @deps, 'perl-' . ($1 =~ s/::/-/gr)
   } else {
      die "Parse fail\n";
   }
}

exec(dnf => list => @deps);

