#!/usr/bin/env perl

my $cpanfile = shift @ARGV;

if ($cpanfile) {
   die "usage: fedora-list-deps <abs-path-to-cpanfile>"
      unless -r $cpanfile;
} else {
   die "usage: fedora-list-deps <abs-path-to-cpanfile>";
}

my @deps;
foreach (qx(cpanfile-dump --with-all-features $cpanfile)) {
   chomp;
   push @deps, 'perl-' . ($_ =~ s/::/-/gr);
}
my @list = map {if (m/^perl-[\w+\.\-]++/p) {${^MATCH}} else {()}} qx(dnf list @deps);
print join("\n", @list) . "\n";
